# Uncomment the next line to define a global platform for your project
# TODO: Make a cookiecutter variable for `iOS Deployment Target`
platform :ios, '11.0'

target '{{ cookiecutter.app_name }}' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for {{ cookiecutter.app_name }}
  pod 'R.swift'
  pod 'SwiftLint'
  
  target '{{ cookiecutter.app_name }}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '{{ cookiecutter.app_name }}UITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
