# Uncomment the next line to define a global platform for your project
# TODO: Make a cookiecutter variable for `iOS Deployment Target`
platform :ios, '11.0'

target '{{ cookiecutter.app_name }}' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for {{ cookiecutter.app_name }}
  pod 'R.swift', '~> 5.0'
  pod 'SwiftLint', '~> 0.33.0'
  pod 'NVActivityIndicatorView', '= 4.6.1'
  pod 'Toast-Swift', '~> 4.0'
  pod 'Alamofire', '= 4.8.2'
  {% if cookiecutter.side_menu == "Yes" %}
    pod 'SideMenu', '~> 5.0'
  {% endif %}
  {% if cookiecutter.pager_tab_strip == "Yes" %}
    pod 'XLPagerTabStrip', '~>8.1'
  {% endif %}
  {% if cookiecutter.cosmos == "Yes" %}
    pod 'Cosmos', '~> 18.0'
  {% endif %}
  
  target '{{ cookiecutter.app_name }}Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '{{ cookiecutter.app_name }}UITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
