# paths to ignore during linting. overridden by `included`.
# paths are relative to the source code project main directory `$SRCROOT`

excluded:
  - {{ cookiecutter.app_name }}/Resources/R.generated.swift
  - Pods/
  - Carthage/

# Rules

opt_in_rules:
  - conditional_returns_on_newline
  - fatal_error_message
  - overridden_super_call
  - closure_end_indentation
  - closure_spacing
  - empty_string
  - explicit_init
  - first_where
  - joined_default_parameter
  - multiline_parameters
  - prohibited_super_call
  - sorted_first_last
  - untyped_error_in_catch
  - file_header

force_cast: warning
force_try: warning

colon:
  apply_to_dictionaries: false

identifier_name:
  excluded:
    - id
    - URL

# Constants

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 400

line_length: 110

function_parameter_count: 4

function_body_length:
  warning: 150
  error: 200

type_name:
  min_length: 4 # only warning
  max_length:
    warning: 40
    error: 50

variable_name_max_length:
  warning: 30
  error: 40

type_contents_order:
  order:
    - case
    - associated_type
    - type_alias
    - subtype
    - [type_property, instance_property]
    - [
        initializer,
        type_method,
        view_life_cycle_method,
        subscript,
        other_method,
        ib_action,
      ]

file_header:
  required_pattern: |
    \/\/
    \/\/  SWIFTLINT_CURRENT_FILENAME
    \/\/  {{ cookiecutter.app_name }}
    \/\/
    \/\/  Created by [A-Z]([a-z]|-[A-Z])*[a-z]( [A-Z]([a-z]|-[A-Z])*[a-z])* on \d{1,2} [A-Z][a-z]{2} \d{4}\.
    \/\/  Copyright © \d{4} .+. All rights reserved.
    \/\/
    
# Custom rules

custom_rules:
  enum_cases_on_newline:
    name: "Enum cases on newline"
    regex: "^\\s*case[\\h\\S]*,(?![^(]*\\))[^:|,]+$"
    message: "Enum cases should always start with a newline."
  accessors_and_observers_on_newline:
    name: "Property accessors and observers on newline"
    regex: "^\\s*(get|set|didSet|willSet)[\\h\\S]\\{[\\h\\S]+$"
    message: "Property accessors and observers should always start with a newline."
